version: "3.9"

services:
  instagram-viewer-api:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - instagram-viewer-network

  redis:
    image: redis:7
    restart: always
    volumes:
      - ./volumes/redis:/var/lib/redis
    networks:
      - instagram-viewer-network
    ports:
      - "6379:6379"

networks:
  instagram-viewer-network:
    name: instagram-viewer-network
