FROM node:20-alpine AS builder

WORKDIR /usr/src/app

COPY package*.json yarn.lock* ./

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build

FROM node:20-alpine AS production

WORKDIR /usr/src/app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY package*.json yarn.lock* ./
RUN yarn install --production --frozen-lockfile

COPY --from=builder /usr/src/app/dist ./dist

EXPOSE 3000

USER appuser

CMD ["node", "dist/src/index.js"]

